type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
}

type Memorial @table {
  creator: User!
  firstName: String!
  lastName: String!
  dateOfBirth: Date!
  dateOfDeath: Date!
  isPublic: Boolean!
  createdAt: Timestamp!
  eulogy: String
  profilePhotoUrl: String
}

type Memory @table {
  contributor: User!
  memorial: Memorial!
  type: String!
  createdAt: Timestamp!
  text: String
  imageUrl: String
}

type Comment @table {
  author: User!
  text: String!
  createdAt: Timestamp!
  memorial: Memorial
  memory: Memory
}